### ISSUE TITLE
Not working in 4.4.2

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Gnzlt/AndroidVisionQRReader#1]
I ran the sample project on a HTC 816 (running Android 4.4.2) but it doesn't seem to scan the QR code.

No errors, crashes occur either.

**Comment by Gnzlt** [comment]
I had this exact problem with a Galaxy S4 until I commit the Autofocus fix but you can try updating the Google Play Services version.
Anyways, there have been so many changes on the original [Google API Samples](https://github.com/googlesamples/android-vision) since I released this project, so I'm working on it to see what has changed.
Meanwhile, you can keep an eye on the new [barcode-reader sample](https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/BarcodeCaptureActivity.java).

Sorry for the temporary inconvenience

**Comment by Isuru-Nanayakkara** [comment]
I updated my grade file to use the newer version.
`compile 'com.google.android.gms:play-services:8.1.0'`

And somehow it all worked fine! Weird.

**Comment by Gnzlt** [comment]
It makes sense since Google has made so many changes on his last release of Google Play Services and Android Vision API.

Thanks!
